// GET /api/ghost-witness/clc/:hash
// Public endpoint — anyone with the audit hash can verify the CLC.
// Does NOT expose businessKey.

import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { sql } from "drizzle-orm";

export async function GET(
  _req: NextRequest,
  { params }: { params: { hash: string } }
) {
  const { hash } = params;

  if (!hash || hash.length < 8) {
    return NextResponse.json({ error: "Invalid hash." }, { status: 400 });
  }

  const result = await db.execute(sql`
    SELECT audit_id, platform, consistent, confidence, flags, tx_hash,
           clc_url, claim_count, status, completed_at, created_at
    FROM ghost_witness_audits
    WHERE audit_hash = ${hash} OR audit_id = ${hash}
    LIMIT 1
  `);

  if (result.rows.length === 0) {
    return NextResponse.json({ error: "Certificate not found." }, { status: 404 });
  }

  const row = result.rows[0] as Record<string, unknown>;

  return NextResponse.json({
    verified: true,
    certificate: {
      audit_hash:  hash,
      platform:    row.platform,
      consistent:  row.consistent,
      score:       row.confidence,
      flags:       row.flags,
      claim_count: row.claim_count,
      status:      row.status,
      issued_at:   row.created_at,
      settled_at:  row.completed_at,
      tx_hash:     row.tx_hash,
      clc_url:     row.clc_url,
    },
    message: "This certificate was generated by ExergyNet Ghost-Witness LNES-05 and anchored on Base L2.",
  });
}
